const CONFIG = {
  SCRIPT_URL: 'https://script.google.com/macros/s/AKfycbyMneOQwAwXIIS1LIJXHTLlH128_Y9XvCJCcjEgvVs3vo8eXvabucWhW-N9vCfGHVpN/exec',
  PONTOS_PLACAR_EXATO: 8,
  PONTOS_SALDO_CERTO: 5,
  PONTOS_VENCEDOR_CERTO: 3,
  PONTOS_CAMPEAO: 20
};
