const CONFIG = {
  SCRIPT_URL: 'https://script.google.com/macros/s/AKfycbwXCz224RZHDA34Xv7bHRYkwUvjOdmHR-vTuSu3a3GBf2r7Z27Igh7gHVNsLx6QsGm_/exec',
  PONTOS_PLACAR_EXATO: 8,
  PONTOS_SALDO_CERTO: 5,
  PONTOS_VENCEDOR_CERTO: 3,
  PONTOS_CAMPEAO: 20
};
